apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2khf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2khf
    app.kubernetes.io/part-of: lpardo-test-app
  name: devfile-sample-2khf
  namespace: lpardo-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2khf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2khf
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:212775e5ea00a6db4235877a969e609479d461c459e1066889023a994b6a5574
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
