apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2khf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2khf
    app.kubernetes.io/part-of: lpardo-test-app
  name: devfile-sample-2khf
  namespace: lpardo-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-2khf
status:
  loadBalancer: {}
